<?xml version="1.0"?>
<package format="3">
  <name>offboard_cpp</name>
  <version>0.1.0</version>
  <description>Minimal direct uXRCE-DDS PX4 Offboard mission.</description>
  <maintainer email="863237849@qq.com">orangepi</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>std_srvs</depend>
  <depend>px4_msgs</depend>
  <depend>boomboom_common</depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <test_depend>ament_cmake_gtest</test_depend>
  <export><build_type>ament_cmake</build_type></export>
</package>
